name: pyrmd
dependencies:
- openssl=1.0.2d=0
- pip=7.1.2=py27_0
- python=2.7.11=0
- readline=6.2=2
- reportlab=3.2.0=py27_0
- setuptools=19.1.1=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0

